Merge latest pull requests to master
smash-transport/smash pull request #24
Opened 2021-03-18 15:27 UTC by stdnmr

Branch includes the latest PRs that were first merged to a separate branch to take care of some housekeeping like code formatting or updating the changelog file instead of merging to and working on the public master directly.

2021-06-19 18:28 UTC, gabriele-inghirami requested changes
We have a problem of compatibility between gcc-4.8 and Rivet, which requires a more recent compiler (supporting c++14 std).
Instead of commenting the code, I preferred to open a PR on this branch to submit you an example of the changes that might be done.
Feel free to pick up what you feel appropriate and discard the rest.

2021-06-23 09:39 UTC, gabriele-inghirami approved these changes
OK

2021-06-23 09:47 UTC, stdnmr commented
@akschaefer could you back up @gabriele-inghirami here

2021-06-23 09:47 UTC, akschaefer approved these changes

2021-06-23 09:49 UTC, merged